### 测试接口
GET http://localhost:8000/business/test
Accept: application/json

### 获取全部车次
GET http://localhost:8000/business/admin/train/query-all
Accept: application/json

### 获取全部车站
GET http://localhost:8000/business/admin/station/query-all
Accept: application/json

### 生成车次座位
GET http://localhost:8000/business/admin/train/gen-seat/G1
Accept: application/json


### 获取每日车票 - 缓存测试
GET http://localhost:8000/business/admin/daily-train-ticket/query-list?page=1&size=5
Accept: application/json

### 获取每日车票 - 缓存测试2
GET http://localhost:8000/business/admin/daily-train-ticket/query-list2?page=1&size=5
Accept: application/json

### 获取每日车票 - 缓存测试3
GET http://localhost:8000/business/admin/daily-train-ticket/query-list3?page=1&size=5&trainCode=G1
Content-Type: application/json