### 测试接口
GET http://localhost:8001/member/test
Accept: application/json

### 网关测试接口
GET http://localhost:8000/member/test
Accept: application/json

### member表数量测试
GET http://localhost:8000/member/member/count
Accept: application/json

### 注册
POST http://localhost:8000/member/member/register
Content-Type: application/json

{
  "mobile": "18962521754"
}

### 发送短信
POST http://localhost:8000/member/member/code
Content-Type: application/json

{
  "mobile": "18962521754"
}

### 登录
POST http://localhost:8000/member/member/login
Content-Type: application/json

{
  "mobile": "18962521758",
  "code": "8888"
}