### 添加乘客
POST http://localhost:8000/member/passenger/save
Content-Type: application/json
token: {{token}}

{
  "name": "flobby",
  "idCard": "320506200108282222",
  "type": "1"
}


### 查询乘客
GET http://localhost:8000/member/passenger/query?page=1&size=2
Content-Type: application/json
token: {{token}}
