server:
  port: 8000

spring:
  application:
    name: train-gateway
  cloud:
    gateway:
      routes:
        - id: train-member
          uri: http://127.0.0.1:8001
          predicates:
            - Path=/member/**