server:
  port: 8000

spring:
  application:
    name: train-gateway
  cloud:
    gateway:
      routes:
        - id: train-member
          uri: http://127.0.0.1:8001
          predicates:
            - Path=/member/**
        - id: train-business
          uri: http://127.0.0.1:8002
          predicates:
            - Path=/business/**
      globalcors:
        cors-configurations:
            '[/**]':
                allowedMethods: "*"
                allowedHeaders: "*"
                allowCredentials: true
                allowedOriginPatterns: "*"
                maxAge: 3600