server:
  port: 8000

spring:
  application:
    name: train-gateway
  cloud:
    gateway:
      routes:
        - id: train-member
          uri: lb://train-member
          predicates:
            - Path=/member/**
        - id: train-business
          uri: lb://train-business
          predicates:
            - Path=/business/**
        - id: train-batch
          uri: lb://train-batch
          predicates:
            - Path=/batch/**
      globalcors:
        cors-configurations:
            '[/**]':
                allowedMethods: "*"
                allowedHeaders: "*"
                allowCredentials: true
                allowedOriginPatterns: "*"
                maxAge: 3600
    nacos:
      discovery:
          server-addr: 106.15.104.19:8848