server:
  # 随机端口号
  port: 0
  servlet:
    context-path: /business

spring:
  application:
    name: train-business
  datasource:
    url: jdbc:mysql://rm-cn-4xl3e1zjr00016fo.rwlb.rds.aliyuncs.com:3306/train_business?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: train
    password: Train123
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 106.15.104.19:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080

  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
    redis:
      use-key-prefix: true
      key-prefix: train_cache_
      cache-null-values: true
      time-to-live: 60s

rocketmq:
  name-server: http://106.14.246.27:9876
  producer:
    group: default

mybatis:
  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    local-cache-scope: statement

logging:
  level:
    top.flobby.train.business.mapper: trace