server:
  port: 8003
  servlet:
    context-path: /batch

spring:
  application:
    name: train-batch
  datasource:
    url: jdbc:mysql://rm-cn-4xl3e1zjr00016fo.rwlb.rds.aliyuncs.com:3306/train_batch?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: train
    password: Train123
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 106.15.104.19:8848

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    top.flobby.train.batch.mapper: trace